title: Tre Owens
logo: assets/headshot.png
description: BI Analyst with 9 years of experience across various industries, adept at providing crucial data insights for enhancing outcomes and driving profit. Expert in large dataset visualization, identifying key metrics, and crafting strategies to bolster business growth through detailed analytical support.
# show_downloads: true
theme: jekyll-theme-minimal
