title: Tre Owens
logo: assets/headshot.png
description: Technical Skills:

Advanced SQL | Business Intelligence | Data Analysis | Data Visualization | Quantitative Analysis | Client Consultation | Data Wrangling | A/B Testing | Agile Experience | Process Modeling | CRM Experience
Tools:

SQL | Tableau | Power BI | Snowflake | Looker | LookML | Excel | Python | GitHub
theme: jekyll-theme-minimal
